### ISSUE TITLE
Client should use http instead of https

### ISSUE THREAD

**Issue by jkawamoto** [lukechampine/shard#3]
I'm afraid that it might not work because the server doesn't use https i.e. `ListenAndServeTLS`

https://github.com/lukechampine/shard/blob/55ee50ba70b592ae3fa5d82a73bfa413f6c30b0f/cmd/shard/main.go#L51

It'd be better to use `http` instead of `https` here
https://github.com/lukechampine/shard/blob/55ee50ba70b592ae3fa5d82a73bfa413f6c30b0f/client.go#L110

Related to https://github.com/lukechampine/muse/issues/4.

**Comment by lukechampine** [comment]
In my experience it's easier to serve HTTP over localhost and then use a reverse proxy (e.g. NGINX) to expose a public HTTPS server. At the same time, for security reasons we want HTTPS to be the default; so if you want plain HTTP, you have to ask for it explicitly.

On the other hand...will Go's http client automatically follow HTTP->HTTPS redirects? If so, then maybe prepending just `http://` is fine. The proxy server can be responsible for redirecting to HTTPS.

**Comment by jkawamoto** [comment]
Actually, I'm wondering if we really need to consider security because `shard` only serves public information.

If users should use HTTPS instead of HTTP, I think it'd be better if `shard` itself supports it. Go has functions for it. For example, if the user gives a cert file and a key file, then use `ListenAndServeTLS`, otherwise use `ListenAndServe`. We can run NGINX as a side-car but configuring NGINX properly isn't easy. 

Btw, from the doc https://golang.org/pkg/net/http/#Get, http.Get follows redirects. 
> Get issues a GET to the specified URL. If the response is one of the following redirect codes, Get follows the redirect, up to a maximum of 10 redirects:

So, using `http://` should be fine in any cases.

**Comment by lukechampine** [comment]
> Actually, I'm wondering if we really need to consider security because `shard` only serves public information.

True, but you still leak metadata: an attacker could see which hosts you're looking up. The argument for HTTPS is much weaker here than for e.g. `muse`, but there's really no reason *not* to use HTTPS (except that dealing with certs is annoying sometimes).

> If users should use HTTPS instead of HTTP, I think it'd be better if `shard` itself supports it.

I'm open to it, but I'm not inclined to implement this until someone actually needs it. If NGINX is too difficulty, Caddy supposedly makes serving HTTPS super easy (though I haven't tried it myself).

Given that Go handles the redirect automatically, I've pushed a commit that removes the HTTPS default: https://github.com/lukechampine/shard/commit/8f942e9fb050aad5d04562ef8eaa490dcfb7268b
